services:
  - type: web
    name: enterprise-rag-assistant
    env: python
    runtime: python-3.11.0
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPEN_AI_KEY
        sync: false
